CREATE TABLE employee
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    surname VARCHAR(255),
    CONSTRAINT employee_pkey PRIMARY KEY (id)
);

CREATE TABLE task
(
    employee_id BIGINT,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date  TIMESTAMP WITHOUT TIME ZONE,
    description VARCHAR(255),
    title       VARCHAR(255),
    CONSTRAINT task_pkey PRIMARY KEY (id)
);

ALTER TABLE employee
    ADD CONSTRAINT uc_2df0c468e61c84d663262329b UNIQUE (name, surname);

ALTER TABLE task
    ADD CONSTRAINT fkmeqi2abtbehx871tag4op3hag FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE NO ACTION;