CREATE TABLE employee
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    surname VARCHAR(255),
    CONSTRAINT pk_employee PRIMARY KEY (id)
);


CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    start_date  TIMESTAMP WITHOUT TIME ZONE,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    employee_id BIGINT,
    CONSTRAINT pk_task PRIMARY KEY (id)
);


ALTER TABLE employee
    ADD CONSTRAINT uc_2df0c468e61c84d663262329b UNIQUE (name, surname);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);